POST http://localhost:8000/users
Content-Type: application/json

{
    "username": "Ronalis",
    "email": "ronalissaputra@gmail.com",
    "password": "ronalis321",
    "confpassword": "ronalis321"
}

###
DELETE http://localhost:8000/user/13

###

POST http://localhost:8000/login
Content-Type: application/json

{
    "email": "ronalissaputra@gmail.com",
    "password": "ronalis321"
}

###!SECTION

DELETE http://localhost:8000/logout